

let myjokes = [
  {
    category: "Dark",
    type: "single",
    joke: "My little daughter came to me all excited, saying \"Daddy! Daddy! Guess how old I'll be in June!\"\n\"Oh I don't know princess, why don't you tell me?\" I said. She gave me a huge smile and held up four fingers.\nIt's now three hours later, police have joined in and she still won't say where she got them.",
    flags: {
      nsfw: false,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: false,
    },
    id: 165,
    safe: false,
    lang: "en",
  },
  {
    category: "Misc",
    type: "single",
    joke: "Schrödinger's cat walks into a bar and doesn't.",
    flags: {
      nsfw: false,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: false,
    },
    id: 197,
    safe: true,
    lang: "en",
  },
  {
    category: "Programming",
    type: "single",
    joke: 'Two SQL tables sit at the bar. A query approaches and asks "Can I join you?"',
    flags: {
      nsfw: false,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: false,
    },
    id: 221,
    safe: true,
    lang: "en",
  },
  {
    category: "Programming",
    type: "single",
    joke: 'A man is smoking a cigarette and blowing smoke rings into the air. His girlfriend becomes irritated with the smoke and says "Can\'t you see the warning on the cigarette pack? Smoking is hazardous to your health!" to which the man replies, "I am a programmer.  We don\'t worry about warnings; we only worry about errors."',
    flags: {
      nsfw: false,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: false,
    },
    id: 38,
    safe: true,
    lang: "en",
  },
  {
    category: "Programming",
    type: "single",
    joke: "I've got a really good UDP joke to tell you but I don’t know if you'll get it.",
    flags: {
      nsfw: false,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: false,
    },
    id: 0,
    safe: true,
    lang: "en",
  },
  {
    category: "Programming",
    type: "single",
    joke: "Knock knock.\nWho's there?\nRecursion.\nRecursion who?\nKnock knock.",
    flags: {
      nsfw: false,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: false,
    },
    id: 180,
    safe: true,
    lang: "en",
  },
  {
    category: "Programming",
    type: "single",
    joke: "Algorithm: A word used by programmers when they don't want to explain how their code works.",
    flags: {
      nsfw: false,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: false,
    },
    id: 51,
    safe: true,
    lang: "en",
  },
  {
    category: "Dark",
    type: "single",
    joke: "I don't know where I stand on abortion. I like killing babies, but I don't like giving women a choice.",
    flags: {
      nsfw: true,
      religious: false,
      political: false,
      racist: false,
      sexist: true,
      explicit: true,
    },
    id: 228,
    safe: false,
    lang: "en",
  },
  {
    category: "Programming",
    type: "single",
    joke: 'Two C strings walk into a bar.\nThe bartender asks "What can I get ya?"\nThe first string says "I\'ll have a gin and tonic."\nThe second string thinks for a minute, then says "I\'ll take a tequila sunriseJF()#$JF(#)$(@J#()$@#())!*FNIN!OBN134ufh1ui34hf9813f8h8384h981h3984h5F!##@"\nThe first string apologizes, "You\'ll have to excuse my friend, he\'s not null-terminated."',
    flags: {
      nsfw: false,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: false,
    },
    id: 28,
    safe: true,
    lang: "en",
  },
  {
    category: "Programming",
    type: "single",
    joke: "How do you tell HTML from HTML5?\n- Try it out in Internet Explorer\n- Did it work?\n- No?\n- It's HTML5.",
    flags: {
      nsfw: false,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: false,
    },
    id: 43,
    safe: true,
    lang: "en",
  },
  {
    category: "Pun",
    type: "single",
    joke: "I was reading a great book about an immortal dog the other day. It was impossible to put down.",
    flags: {
      nsfw: false,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: false,
    },
    id: 236,
    safe: true,
    lang: "en",
  },
  {
    category: "Dark",
    type: "single",
    joke: 'Me and my Jewish friend were eating lunch and I farted. He got mad so I said "cmon man a little gas never killed anyone".',
    flags: {
      nsfw: false,
      religious: false,
      political: false,
      racist: true,
      sexist: false,
      explicit: true,
    },
    id: 103,
    safe: false,
    lang: "en",
  },
  {
    category: "Misc",
    type: "single",
    joke: "Never date a baker. They're too kneady.",
    flags: {
      nsfw: false,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: false,
    },
    safe: true,
    id: 271,
    lang: "en",
  },
  {
    category: "Misc",
    type: "single",
    joke: "Women are like KFC, once you're done with the breasts and thighs, you just have a greasy box to put your bone in.",
    flags: {
      nsfw: true,
      religious: false,
      political: false,
      racist: false,
      sexist: true,
      explicit: true,
    },
    id: 149,
    safe: false,
    lang: "en",
  },
  {
    category: "Dark",
    type: "single",
    joke: 'Nowadays people are so sensitive, you can\'t even say "black paint" anymore.\nInstead, you have to say "Jamal, please paint the fence".',
    flags: {
      nsfw: false,
      religious: false,
      political: false,
      racist: true,
      sexist: false,
      explicit: false,
    },
    id: 133,
    safe: false,
    lang: "en",
  },
  {
    category: "Programming",
    type: "single",
    joke: "I'd tell you a joke about NAT but I would have to translate.",
    flags: {
      nsfw: false,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: false,
    },
    safe: true,
    id: 319,
    lang: "en",
  },
  {
    category: "Misc",
    type: "single",
    joke: "A perfectionist walked into a bar... apparently, the bar was not set high enough.",
    flags: {
      nsfw: false,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: false,
    },
    safe: true,
    id: 288,
    lang: "en",
  },
  {
    category: "Dark",
    type: "single",
    joke: "I didn't vaccinate my 10 kids and the one that survived is fine!",
    flags: {
      nsfw: false,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: false,
    },
    id: 96,
    safe: false,
    lang: "en",
  },
  {
    category: "Dark",
    type: "single",
    joke: 'I hate double standards. Burn a body at a crematorium, you\'re "being a respectful friend." Do it at home and you\'re "destroying evidence."',
    flags: {
      nsfw: false,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: true,
    },
    safe: false,
    id: 274,
    lang: "en",
  },
  {
    category: "Misc",
    type: "single",
    joke: "My wife is really mad at the fact that I have no sense of direction.\nSo I packed up my stuff and right.",
    flags: {
      nsfw: false,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: false,
    },
    id: 201,
    safe: true,
    lang: "en",
  },
];

const jokefunct = () => {
    let index = Math.floor(Math.random() * myjokes.length - 1)
    joke.innerHTML = myjokes[index].joke
}

newjoke.addEventListener('click', jokefunct)